//go:build ignore

// Formula-integrity pipeline for the Oberth Homebrew tap.
//
// The tap is a pure distribution point: Formula/oberth.rb is generated by the
// oberthci/oberth release process and pushed here on every release. This
// pipeline proves the published formula on every push: structural checks
// (version field, four platform URLs, four 64-hex digests, HTTPS only) and an
// independent digest re-derivation — every platform binary is downloaded from
// releases.cloudtaser.io and its SHA256 compared against the formula's
// declared digest.
package main

import "oberth"

func Pipeline(ctx *oberth.Context) oberth.Pipeline {
	return oberth.New().
		Test("formula-integrity",
			oberth.Step{
				Name:    "verify-formula",
				Command: "/bin/sh",
				Args:    []string{"hack/verify-formula.sh"},
				Env:     map[string]string{"HOME": "/tmp"},
			}.WithTimeout(5*oberth.Minute),
		).
		Done()
}
